M48
; DRILL file {KiCad (6.0.2)} date Fri Mar 18 21:37:13 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-18T21:37:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X117.91Y-154.76
X123.69Y-154.76
T2
X72.155Y-148.8
X72.155Y-155.3
X79.155Y-148.8
X79.155Y-155.3
T0
M30
